import type { Property, Workspace } from "@proofboard/shared-types";

export interface GeneratedHarnessFile {
  path: string;
  content: string;
  propertyIds: string[];
}

export interface HarnessBundle {
  files: GeneratedHarnessFile[];
  setupInstructions: string[];
  suggestedCommand: string;
}

export function generateFoundryHarnessBundle(workspace: Workspace, selectedProperties: Property[] = workspace.properties): HarnessBundle {
  const properties = selectedProperties.length > 0 ? selectedProperties : workspace.properties;
  const contractName = workspace.protocolMap.contracts[0]?.name ?? "Vault";
  const sourcePath = workspace.protocolMap.contracts[0]?.path ?? "src/Vault.sol";
  const propertyIds = properties.map((property) => property.id);

  return {
    suggestedCommand: "forge test --match-contract ProofboardVaultInvariant",
    setupInstructions: [
      "Copy the generated files into the target repository root while preserving the test/invariants paths.",
      `Update the import in test/invariants/ProofboardVaultInvariant.t.sol if ${sourcePath} is not the vault source path.`,
      "Wire the vault constructor and asset deployment in setUp before treating any result as evidence.",
      "Run the suggested forge test command locally and paste the raw output into ProofBoard Results."
    ],
    files: [
      {
        path: "test/invariants/ProofboardVaultInvariant.t.sol",
        propertyIds,
        content: invariantContract(contractName, sourcePath, properties)
      },
      {
        path: "test/invariants/handlers/VaultHandler.sol",
        propertyIds,
        content: handlerContract(contractName, properties)
      },
      {
        path: "test/invariants/actors/VaultActors.sol",
        propertyIds,
        content: actorModelContract()
      },
      {
        path: "test/invariants/mocks/MockERC20.sol",
        propertyIds: [],
        content: mockErc20Contract()
      },
      {
        path: "test/invariants/mocks/FeeOnTransferToken.sol",
        propertyIds: ["assumption_no_fee_on_transfer"],
        content: feeOnTransferTokenContract()
      },
      {
        path: "test/invariants/mocks/RebasingToken.sol",
        propertyIds: ["assumption_no_rebase"],
        content: rebasingTokenContract()
      },
      {
        path: "test/invariants/README.md",
        propertyIds,
        content: harnessReadme(workspace, properties)
      }
    ]
  };
}

function invariantContract(contractName: string, sourcePath: string, properties: Property[]) {
  const invariantFunctions = properties.map((property) => {
    const name = invariantName(property);
    return `    /// @dev ProofBoard property: ${property.id}
    /// ${property.text}
    function invariant_${name}() public {
        handler.assertProperty("${property.id}");
    }`;
  });

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {${contractName}} from "../../${sourcePath}";
import {VaultHandler} from "./handlers/VaultHandler.sol";
import {VaultActors} from "./actors/VaultActors.sol";
import {MockERC20} from "./mocks/MockERC20.sol";

/// @notice Scaffold generated by ProofBoard. It is not proof of safety until run and reviewed.
contract ProofboardVaultInvariant is Test {
    ${contractName} internal vault;
    MockERC20 internal asset;
    VaultActors internal actors;
    VaultHandler internal handler;

    function setUp() public {
        asset = new MockERC20("Mock Asset", "MCK", 18);
        actors = new VaultActors();

        // TODO: Deploy ${contractName} with the real constructor arguments.
        // vault = new ${contractName}(...);
        handler = new VaultHandler(address(vault), address(asset), actors);
        targetContract(address(handler));
    }

${invariantFunctions.join("\n\n")}
}
`;
}

function handlerContract(contractName: string, properties: Property[]) {
  const propertyCases = properties
    .map((property) => `        if (propertyIdHash == keccak256(bytes("${property.id}"))) return _assert_${invariantName(property)}();`)
    .join("\n");
  const assertionFunctions = properties
    .map(
      (property) => `    function _assert_${invariantName(property)}() internal view returns (bool) {
        // ProofBoard property ${property.id}: ${property.text}
        // TODO: Replace scaffold assertion with protocol-specific accounting checks.
        return vault != address(0) && asset != address(0);
    }`
    )
    .join("\n\n");

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {VaultActors} from "../actors/VaultActors.sol";
import {MockERC20} from "../mocks/MockERC20.sol";

/// @notice Handler scaffold for ${contractName}. Add bounded calls for deposit, mint, withdraw, redeem, donations, and admin flows.
contract VaultHandler {
    address public immutable vault;
    address public immutable asset;
    VaultActors public immutable actors;

    constructor(address vault_, address asset_, VaultActors actors_) {
        vault = vault_;
        asset = asset_;
        actors = actors_;
    }

    function deposit(uint256 assets, uint256 actorSeed) public {
        address actor = actors.actor(actorSeed);
        assets = boundAmount(assets);
        MockERC20(asset).mint(actor, assets);
        // TODO: prank actor, approve vault, and call deposit.
    }

    function withdraw(uint256 assets, uint256 actorSeed) public {
        address actor = actors.actor(actorSeed);
        assets = boundAmount(assets);
        actor;
        // TODO: prank actor and call withdraw/redeem with bounded owned shares.
    }

    function donate(uint256 assets) public {
        assets = boundAmount(assets);
        MockERC20(asset).mint(address(this), assets);
        MockERC20(asset).transfer(vault, assets);
    }

    function assertProperty(string memory propertyId) public view returns (bool) {
        bytes32 propertyIdHash = keccak256(bytes(propertyId));
${propertyCases || "        propertyIdHash;"}
        return false;
    }

${assertionFunctions || "    function _noProperties() internal pure returns (bool) {\n        return false;\n    }"}

    function boundAmount(uint256 amount) internal pure returns (uint256) {
        return 1 + (amount % 1_000_000 ether);
    }
}
`;
}

function actorModelContract() {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Minimal actor model scaffold. Expand roles before claiming multi-actor evidence.
contract VaultActors {
    address[] internal actors;

    constructor() {
        actors.push(address(0xA11CE));
        actors.push(address(0xB0B));
        actors.push(address(0xCAFE));
    }

    function actor(uint256 seed) public view returns (address) {
        return actors[seed % actors.length];
    }

    function allActors() external view returns (address[] memory) {
        return actors;
    }
}
`;
}

function mockErc20Contract() {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

contract MockERC20 {
    string public name;
    string public symbol;
    uint8 public immutable decimals;
    uint256 public totalSupply;
    mapping(address => uint256) public balanceOf;
    mapping(address => mapping(address => uint256)) public allowance;

    constructor(string memory name_, string memory symbol_, uint8 decimals_) {
        name = name_;
        symbol = symbol_;
        decimals = decimals_;
    }

    function approve(address spender, uint256 amount) external returns (bool) {
        allowance[msg.sender][spender] = amount;
        return true;
    }

    function transfer(address to, uint256 amount) external returns (bool) {
        _transfer(msg.sender, to, amount);
        return true;
    }

    function transferFrom(address from, address to, uint256 amount) external returns (bool) {
        uint256 allowed = allowance[from][msg.sender];
        require(allowed >= amount, "ALLOWANCE");
        allowance[from][msg.sender] = allowed - amount;
        _transfer(from, to, amount);
        return true;
    }

    function mint(address to, uint256 amount) public virtual {
        balanceOf[to] += amount;
        totalSupply += amount;
    }

    function _transfer(address from, address to, uint256 amount) internal virtual {
        require(balanceOf[from] >= amount, "BALANCE");
        balanceOf[from] -= amount;
        balanceOf[to] += amount;
    }
}
`;
}

function feeOnTransferTokenContract() {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {MockERC20} from "./MockERC20.sol";

contract FeeOnTransferToken is MockERC20 {
    uint256 public feeBps = 100;
    address public feeRecipient = address(0xFEE);

    constructor() MockERC20("Fee Token", "FEE", 18) {}

    function setFeeBps(uint256 nextFeeBps) external {
        require(nextFeeBps <= 1_000, "FEE_TOO_HIGH");
        feeBps = nextFeeBps;
    }

    function _transfer(address from, address to, uint256 amount) internal override {
        uint256 fee = (amount * feeBps) / 10_000;
        uint256 received = amount - fee;
        require(balanceOf[from] >= amount, "BALANCE");
        balanceOf[from] -= amount;
        balanceOf[to] += received;
        balanceOf[feeRecipient] += fee;
    }
}
`;
}

function rebasingTokenContract() {
  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {MockERC20} from "./MockERC20.sol";

contract RebasingToken is MockERC20 {
    constructor() MockERC20("Rebasing Token", "RBS", 18) {}

    function positiveRebase(address holder, uint256 amount) external {
        mint(holder, amount);
    }

    function negativeRebase(address holder, uint256 amount) external {
        require(balanceOf[holder] >= amount, "BALANCE");
        balanceOf[holder] -= amount;
        totalSupply -= amount;
    }
}
`;
}

function harnessReadme(workspace: Workspace, properties: Property[]) {
  const lines = properties.map((property) => `- ${property.id}: ${property.text}`);
  return `# ProofBoard Foundry Harness Scaffold

Workspace: ${workspace.name || workspace.id}

This generated bundle is scaffold code, not a proof of safety. Treat results as evidence only after a human reviewer wires constructors, handlers, actor roles, and protocol-specific assertions.

## Selected properties
${lines.join("\n") || "- No properties selected."}

## Suggested command
\`\`\`sh
forge test --match-contract ProofboardVaultInvariant
\`\`\`
`;
}

function invariantName(property: Property) {
  const words = property.id
    .replace(/^property_/, "")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean);

  const name = words
    .map((word, index) => (index === 0 ? word.toLowerCase() : word.charAt(0).toUpperCase() + word.slice(1)))
    .join("");

  return name || "generatedProperty";
}
